version: "3.7"
services:
  spark-master:
    image: spydernaz/spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: spydernaz/spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  notebook:
    build: docker/
    #image: datadrone/deeplearn_pytorch:latest
    ports:
      - "9200:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_OPTS='--master=spark://spark-master:7077'
    ipc: host
    volumes:
       - /home/brian/Workspace:/home/jovyan/work
