version: "3.7"
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=6G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
       - /home/brian/Workspace/spark_learn/apps:/opt/spark-apps
       - /home/brian/Workspace/spark_learn/data:/opt/spark-data
  notebook:
    #build: docker/
    image: datadrone/spark_notebook:2.4.5-hadoop2.7
    ports:
      - "9200:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JAVA_HOME=/usr
      - SPARK_MASTER=spark://spark-master:7077
    ipc: host
    volumes:
       - /home/brian/Workspace:/home/jovyan/work
       - ./data:/opt/spark-data
